### PR TITLE
Ft job portal refactoring

### PR DESCRIPTION
**Pull request by surapuramakhil**
Refactoring changes
- job poral
- jobs pages
- job page
- Application page
- Job Manager, Job Applier - won't be having direct access to the driver, interaction must be done via job portal object.

PS: Linked code here is earlier versions (currently broken)

### CODE REVIEW

**Comment by surapuramakhil** [comment]
@sarob as this review might be useful for your feature #831 

@feder-cr as you own next creating plugins #975

**Review by feder-cr — DISMISSED** [review]
the README needs to be totally rewritten

**Comment by surapuramakhil** [comment]
> the README needs to be totally rewritten

I believe this task #976 will handle that.

**Comment by feder-cr** [comment]
@surapuramakhil @sarob 

### Proposal: Enhance Plugin Management with a Clearer Pattern

Currently, our plugin management lacks a precise and structured approach, which could lead to maintenance challenges and reduced extensibility as the project scales. To address this, I propose adopting **Pluggy**, a lightweight and flexible framework specifically designed for plugin systems in Python. 

**Why Pluggy?**
- Provides a clear mechanism for defining and implementing plugin hooks.
- Supports dynamic plugin loading and priority handling.
- Simplifies plugin registration and ensures scalability.

### Recommended Resources
To get started and better understand the benefits of Pluggy, here are some helpful links:
1. [[Official Pluggy Documentation](https://pluggy.readthedocs.io/)](https://pluggy.readthedocs.io/)
2. [[Build Plugins with Pluggy](https://kracekumar.com/post/build_plugins_with_pluggy/)](https://kracekumar.com/post/build_plugins_with_pluggy/)
3. [[A Minimal Pluggy Example](https://dev.to/waylonwalker/a-minimal-pluggy-example-3mp0)](https://dev.to/waylonwalker/a-minimal-pluggy-example-3mp0)
4. [[Pluggable Architecture with Python](https://waylonwalker.com/python-pluggable-architecture/)](https://waylonwalker.com/python-pluggable-architecture/)

**Review by feder-cr — CHANGES_REQUESTED** [review]
Proposal: Enhance Plugin Management with a Clearer Pattern
Currently, our plugin management lacks a precise and structured approach, which could lead to maintenance challenges and reduced extensibility as the project scales. To address this, I propose adopting Pluggy, a lightweight and flexible framework specifically designed for plugin systems in Python.

Why Pluggy?

Provides a clear mechanism for defining and implementing plugin hooks.
Supports dynamic plugin loading and priority handling.
Simplifies plugin registration and ensures scalability.
Recommended Resources
To get started and better understand the benefits of Pluggy, here are some helpful links:

https://pluggy.readthedocs.io/
https://kracekumar.com/post/build_plugins_with_pluggy/
https://dev.to/waylonwalker/a-minimal-pluggy-example-3mp0
https://waylonwalker.com/python-pluggable-architecture/

**Comment by surapuramakhil** [comment]
> Proposal: Enhance Plugin Management with a Clearer Pattern
> 
> Currently, our plugin management lacks a precise and structured approach, which could lead to maintenance challenges and reduced extensibility as the project scales. To address this, I propose adopting Pluggy, a lightweight and flexible framework specifically designed for plugin systems in Python.
> 
> Why Pluggy?
> 
> Provides a clear mechanism for defining and implementing plugin hooks. Supports dynamic plugin loading and priority handling. Simplifies plugin registration and ensures scalability. Recommended Resources
> 
> To get started and better understand the benefits of Pluggy, here are some helpful links:
> 
> https://pluggy.readthedocs.io/ https://kracekumar.com/post/build_plugins_with_pluggy/ https://dev.to/waylonwalker/a-minimal-pluggy-example-3mp0 https://waylonwalker.com/python-pluggable-architecture/

this is out of scope, for this PR (this PR only addresses - refactoring, not focus on plugin, but still extendable for plugin)

**Comment by feder-cr** [comment]
@surapuramakhil ok

**Review by feder-cr — APPROVED** [review]

**Pull request merged**
