### PR TITLE
BREAKING: [WIP] UV initial support

### PR DESCRIPTION
**Pull request by wahmedswl**

### CODE REVIEW

**Comment by surapuramakhil** [comment]
@wahmedswl  can you attach issue you are working on, it there isn't one kindly create it.

**Comment by wahmedswl** [comment]
@surapuramakhil https://github.com/AIHawk-app/Auto_Jobs_Applier/issues/740 is created. UV will help increasing developer happiness and CI/CD times as it's much faster than PIP.

**Comment by surapuramakhil** [comment]
@wahmedswl Are you working on this PR? you also need to take care of

- [ ]  updating GitHub actions. CI/CD
- [ ]  updating readME

**Comment by wahmedswl** [comment]
@surapuramakhil Yes, i got distracted. That make sense; i will update readme and CI/CD scripts as well. I have tried to run it with UV and it seems to work. If test cases are passing, we are good?

Thanks

**Comment by surapuramakhil** [comment]
> @surapuramakhil Yes, i got distracted. That make sense; i will update readme and CI/CD scripts as well. I have tried to run it with UV and it seems to work. If test cases are passing, we are good?
> 
> Thanks

Test cases aren't strong yet.

here is the checklist

- [ ] take project from scratch
- [ ] install all required dependencies using UV
- [ ] run project - make sure code runs through entire critical workflows - at least submitting one or two applications
- [ ] then update ReadME, CI/CD pipelines

If PR is ready, then change it from draft state to open state.

**Comment by feder-cr** [comment]
@wahmedswl hi, any updates?

**Comment by feder-cr** [comment]
@wahmedswl ?

**Pull request closed without merging**
