### PR TITLE
Fix LinkedIn changes in naming CLASS_NAME

### PR DESCRIPTION
**Pull request by Diegu1**

### CODE REVIEW

**Comment by surapuramakhil** [comment]
@Diegu1 it closed on release process. I could see some other changes too. are those required?

in _create_and_upload_resume

you can raise PR to release branch 4.1

**Comment by surapuramakhil** [comment]
@Diegu1 once you confirm its working, happy to merge

**Review by cjbbb — APPROVED** [review]

**Comment by surapuramakhil** [comment]
@cjbbb is this working?

**Comment by cjbbb** [comment]
> @cjbbb is this working?
> 
> @Diegu1 request to resolve merge conflits

the bot not working right now. we need to change the class name since linkedin changed their front-end. Maybe request more changes.

**Comment by surapuramakhil** [comment]
don't you think approving it gives wrong signals maintainers would merge it and again deal with revert / fixing these changes.

**Comment by cjbbb** [comment]
> don't you think approving it gives wrong signals, maintainers would merge it and again deal with revert / fixing these changes.

sorry for my confused reply. those changes are correct based on new changes on Linkedin Front-end. However, we need more elements changes to make the bot work

**Pull request closed without merging**
